package app.web.safetravels.entity;

import java.sql.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
@Table(name="booking")

public class Booking {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int bookingId;
	@Getter
	@Setter
	@Column(name="b_username", unique=true)
	private String username;
	private int hotelId;
	@Getter
	@Setter
	private int roomId;
	private Date checkinDate;
	private Date checkoutDate;
	private boolean cancelled;
	private boolean breakfastIncluded;
	@Getter
	@Setter
	private double price;
	@Getter
	@Setter
	private String review;
	@Getter
	@Setter
	private short rating;
	
	
//	/** Constructor without review and rating, which will be created later*/
//	public Booking(int bookingId, String username, int hotelId, int roomId, Date checkinDate, Date checkoutDate,
//			boolean breakfastIncluded) {
//		super();
//		this.bookingId = bookingId;
//		this.username = username;
//		this.roomId = roomId;
//		this.hotelId = hotelId;
//		this.checkinDate = checkinDate;
//		this.checkoutDate = checkoutDate;
//		this.breakfastIncluded = breakfastIncluded;
//	}
//	
	/** Construcyot without bookingId either because this one should be autogenerated.*/
	public Booking(String username, int hotelId, int roomId, Date checkinDate, Date checkoutDate,
			boolean breakfastIncluded) {
		this.username = username;
		this.roomId = roomId;
		this.hotelId = hotelId;
		this.checkinDate = checkinDate;
		this.checkoutDate = checkoutDate;
		this.breakfastIncluded = breakfastIncluded;
	}


	public int getBookingId() {
		return bookingId;
	}
	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	public int getHotelId() {
		return hotelId;
	}
	public void setHotelId(int hotelId) {
		this.hotelId = hotelId;
	}
	public Date getCheckinDate() {
		return checkinDate;
	}
	public void setCheckinDate(Date checkinDate) {
		this.checkinDate = checkinDate;
	}
	public Date getCheckoutDate() {
		return checkoutDate;
	}
	public void setCheckoutDate(Date checkoutDate) {
		this.checkoutDate = checkoutDate;
	}
	public boolean isCancelled() {
		return cancelled;
	}
	
//	public Hotel getHotelByBooking(Booking booking){
//		Hotel hotel = hotel.getHotelById(booking.getHotelId());
//		return 
//	}
	public void setCancelled(boolean cancelled) {
		this.cancelled = cancelled;
	}
	public boolean isBreakfastIncluded() {
		return breakfastIncluded;
	}
	public void setBreakfastIncluded(boolean breakfastIncluded) {
		this.breakfastIncluded = breakfastIncluded;
	}
	
	
}
